name: al_raheeq_library
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 4.5.1+37

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2
  connectivity_plus: ^6.1.3
  get_storage: ^2.1.1
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  delayed_widget: ^1.1.2
  zoom_tap_animation: ^1.1.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  loading_animation_widget: ^1.3.0
  auto_height_grid_view: ^1.0.0
  flutter_rating_bar: ^4.0.1
  path: ^1.9.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  http: ^1.3.0
  permission_handler: ^11.0.1
  audio_waveforms: ^1.0.6
  just_audio: ^0.9.46
  # just_audio_windows: ^0.2.2
  audioplayers: ^6.5.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  archive: ^3.6.1
  flutter_inappwebview: ^6.1.5
  another_xlider: ^3.0.2
  share_plus: ^10.1.2
  printing: ^5.14.2
  pdf: ^3.11.3
  html: ^0.15.4
  intl: ^0.20.2
  audio_service: ^0.18.18
  flutter_local_notifications: ^18.0.1
  google_api_availability: ^5.0.0
  open_file: ^3.5.10
  encrypt: ^5.0.3
  flutter_screenutil: ^5.9.3
  firebase_messaging: ^15.1.6
  firebase_core: ^3.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/svgs/intro/
    - assets/svgs/fill/
    - assets/db/
    - assets/web/js/
    - assets/web/css/
    - assets/web/html/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: dijlah
      fonts:
        - asset: ./assets/fonts/dijlah-reg.ttf
        - asset: ./assets/fonts/dijfont-bold.ttf
          weight: 700
    - family: SegoeUI
      fonts:
        - asset: ./assets/fonts/SegoeUI.ttf
        - asset: ./assets/fonts/SegoeUI-Semilight.ttf
          weight: 700
    - family: abo
      fonts:
        - asset: assets/fonts/abo.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
